name: reviewdog

on: [pull_request]

jobs:
  lint:
    name: Run linters with reviewdog
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          pip install flake8 bandit

      - name: Run flake8 with reviewdog
        uses: reviewdog/action-flake8@v2
        with:
          reporter: github-pr-review
          fail_on_error: false

      - name: Run Bandit with reviewdog
        uses: reviewdog/action-bandit@v1
        with:
          reporter: github-pr-review
          fail_on_error: false

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Restore .NET dependencies
        run: dotnet restore

      - name: Build .NET project and analyze with SonarScanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet tool install --global dotnet-sonarscanner
          dotnet-sonarscanner begin /k:"YourProjectKey" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          dotnet build
          dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
