name: Python Lint with Reviewdog

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install linters and reviewdog
        run: |
          pip install flake8 bandit
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b ./bin
          echo "$PWD/bin" >> $GITHUB_PATH

      - name: Run flake8 with reviewdog
        run: |
          flake8 . --format=default | ./bin/reviewdog -efm="%f:%l:%c: %m" -name="flake8" -reporter=github-pr-review -fail-on-error=false

      - name: Run bandit with reviewdog
        run: |
          bandit -r . -f custom --msg-template "{filename}:{line}: {severity}: {test_id}: {msg}" \
          | ./bin/reviewdog -efm="%f:%l: %m" -name="bandit" -reporter=github-pr-review -fail-on-error=false
