name: Run linters and reviewdog

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python linters and reviewdog
        run: |
          python -m pip install --upgrade pip
          pip install flake8 bandit
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b ./bin
        shell: bash

      - name: Run flake8 with reviewdog
        run: |
          flake8 . --format=default | ./bin/reviewdog \
          -efm="%f:%l:%c: %m" -name="flake8" \
          -reporter=github-pr-review -fail-on-error=false
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format

      - name: Add dotnet tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Run dotnet-format with reviewdog
        run: |
          dotnet format --verify-no-changes --report ./format-report.txt || true
          cat ./format-report.txt | ./bin/reviewdog \
          -efm="%f(%l,%c): %m" -name="dotnet-format" \
          -reporter=github-pr-review -fail-on-error=false
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
